### ISSUE TITLE
Add support for a ?delay param

### ISSUE THREAD

**Issue by humphd** [tonyvugithub/HttpStatusCodeAPI#1]
It would be useful if you could request a response that is delayed by a certain number of s or ms.  For example:

```
# wait for 250 ms before sending back a 200 
GET /status/200?delay=200ms

# wait for 5s before sending back a 201 
GET /status/201?delay=5s

# assume a bare number is a time in seconds, e.g., wait for 5s before sending back a 503 
GET /status/503?delay=5
```

**Comment by tonyvugithub** [comment]
I will add this in shortly. Thanks sir.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
